version: '3.8'

networks:
  my_network:

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  temperature-service:
    build: ./server/temperature-service
    container_name: temperature-service
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - DB_URL=mongodb://mongodb:27017/temperatureDB
    restart: always
    networks:
      - my_network

  websocket-service:
    build: ./server/websocket-service
    container_name: websocket-service
    ports:
      - "6001:6001"
    depends_on:
      - temperature-service
    environment:
      - DB_URL=mongodb://mongodb:27017/temperatureDB
    restart: always
    networks:
      - my_network

  sensor-service:
    build: ./server/sensor-service
    container_name: sensor-service
    depends_on:
      - websocket-service
    restart: always
    networks:
      - my_network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - websocket-service
    networks:
      - my_network

volumes:
  mongodb_data:
